// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error)
	DeleteAddressFromAccount(ctx context.Context, accountUuid uuid.UUID) error
	GetAccountById(ctx context.Context, accountUuid uuid.UUID) (Account, error)
	GetAddressByAccount(ctx context.Context, accountUuid uuid.UUID) (Address, error)
	GetAddressById(ctx context.Context, addressUuid uuid.UUID) (Address, error)
	GetTradeById(ctx context.Context, tradeUuid uuid.UUID) (Trade, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListTradesByAccount(ctx context.Context, accountUuid uuid.UUID) ([]Trade, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateTrade(ctx context.Context, arg UpdateTradeParams) (Trade, error)
}

var _ Querier = (*Queries)(nil)
