version: '2'

services:
  stock_db:
    restart: unless-stopped
    image: postgres:10-alpine
    ports:
      - '6432:5432'
    container_name: stock_db
    volumes:
        - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: trade, trade_test
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'golang'